---
title: "Population and community ecology @ Uppsala University"
output: 
  html_document:
    theme: cerulean
    toc: no
    toc_float:
      collapsed: false
---
*Learning coding in R*

R has been developed as a tool for statistical analysis and might by now be the most popular tool in this area. However, R is also a language that we can use to program simulation models in order to investigate population dynamical models in ecology. As such, R can to some extend replace proprietary software packages like MatLab or Mathematica.

This website contains an introduction to some R commands that are essential for coding simulations in R (and, in fact, pretty much everything else you might want to do in R...). Click the tab button and select from the different sections in the drop-down menu. You can work on this material by copying the R-code and pasting it in the script window of your R-Studio application.

This website borrows heavily from chapter 8 of the book 

[S. Allesina and M. Wilmes (2019). Computing Skills for Biologists: A Toolbox (2019).](https://computingskillsforbiologists.com/)

In fact, several parts are produced by simply copy and paste parts from that chapter without further reference.

Material on this website is also inspired by the introductions to R that you can find in these books:

1) [Karline Soetaert and Peter M. J. Herman (2009). A practical guide to ecological modelling: using R as a simulation platform.](https://link.springer.com/book/10.1007\%2F978-1-4020-8624-3)

2) [M. Henry H. Stevens (2010). A Primer of Ecology with R.](http://link.springer.com/book/10.1007\%2F978-0-387-89882-7)

3) [Clement Calenge. The *R* Software for Data Analysis and Modeling. *in* Dennis L. Murray and Brett K. Sandercock (2020). Population Ecology in Practice. Wiley-Blackwell.](https://www.wiley.com/en-se/Population+Ecology+in+Practice-p-9780470674147)

The first two books are available as e-books at the Uppsala University Library.

An excellent and freely available systematic introduction to programming in R can be found [here](https://rstudio-education.github.io/hopr/). Also [this on](https://bookdown.org/ndphillips/YaRrr/) seems to be a nice and gentle introduction. Several topics in R come with a cheat sheet, summarizing the most important elements of that topic, [here the one for base R](https://raw.githubusercontent.com/rstudio/cheatsheets/master/base-r.pdf).

If you are more of a YouTube-person ckeck out [this series](https://www.youtube.com/channel/UCCJJdmc4DlwiWmXVZnMPb0w/playlists) of video tutorials.

**Enjoy!**

Claus



